import type { CategoryValue } from "@/lib/constants";

export type BlogSection =
  | { type: "heading"; text: string }
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }
  | { type: "table"; headers: string[]; rows: string[][]; caption?: string }
  | { type: "callout"; text: string };

export type BlogFaq = { question: string; answer: string };

export type BlogPost = {
  slug: string;
  title: string;
  metaDescription: string;
  targetKeyword: string;
  eyebrow: string;
  intro: string;
  heroImage: string;
  heroAlt: string;
  category: CategoryValue;
  publishDate: string;
  sections: BlogSection[];
  faqs: BlogFaq[];
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: `a2-ghee-vs-regular-ghee`,
    title: `A2 Ghee vs Regular Ghee: Which One Should You Choose?`,
    metaDescription: `A2 ghee vs regular ghee: what the terms mean, how our bilona hand-churned ghee is made, a full comparison table, and how to choose what's right for you.`,
    targetKeyword: `A2 ghee vs regular ghee`,
    eyebrow: `A2 Ghee vs Regular Ghee, Explained`,
    intro: `A2 ghee is made from the milk of cow breeds that naturally produce mostly A2 beta-casein protein, such as Gir and other desi cows, while "regular" ghee is usually made from mixed or unspecified milk sources without that distinction. In practice, though, the bigger everyday difference is often the process behind the jar - which is exactly where our own hand-churned, bilona-made ghee sets itself apart from most regular commercial ghee.`,
    heroImage: `/images/generated/banner-ghee-farm-v4.png`,
    heroAlt: `A2 Gir cow ghee jars beside the herd on the Organic Jaipur Store farm`,
    category: `GHEE` as CategoryValue,
    publishDate: `September 17, 2026`,
    sections: [
      { type: "heading", text: `What Does "A2 Ghee" Actually Mean?` },
      { type: "paragraph", text: `The "A2" in A2 ghee refers to A2 beta-casein, a type of protein found in cow milk. Indigenous Indian cattle breeds - Gir cows and other desi cow breeds among them - are known to naturally produce milk that is predominantly A2 type. On our own farm in Jaipur, we keep Gir cows and desi cows specifically for their milk, and that milk is what goes into our A2 ghee. It's worth being clear that this is a description of the cow's breed and milk protein type, not a certification, a lab result, or a medical claim - we're simply telling you where the milk comes from.` },
      { type: "heading", text: `What Is A1 or "Regular" Ghee, Then?` },
      { type: "paragraph", text: `Most ghee sold under generic or unbranded "regular" labels doesn't specify which protein type its milk contains. It's commonly made from milk pooled across mixed or crossbred cattle herds, which can include cows carrying the A1 beta-casein variant alongside A2. It's also worth noting that the A1/A2 conversation is specific to cow milk - buffalo milk has its own distinct protein profile and isn't really part of that same distinction, which is why we treat our buffalo ghee as its own product rather than labelling it "A2." Beyond the milk protein itself, regular commercial ghee is also usually produced differently at the manufacturing stage, and that difference in process is often what buyers actually notice in taste, aroma and texture.` },
      { type: "heading", text: `How Is Our A2 Ghee Actually Made? (The Bilona Process)` },
      { type: "paragraph", text: `Most regular commercial ghee is made by separating cream directly from milk with a machine, then heating that cream into ghee - a fast, scalable method that skips a traditional step entirely. We make ours the older, slower way, known as the bilona method:` },
      { type: "list", items: [`Milk from Gir cow, desi cow or buffalo is selected, depending on the product.`, `The milk is cultured and left to rest naturally into curd overnight.`, `The curd is hand-churned slowly with a wooden bilona (churner) to separate the butter, or makkhan - the step that machine cream-separation skips altogether.`, `The makkhan is then heated gradually and slow-cooked until the moisture leaves it and it turns into clear, golden, aromatic ghee, which is filtered and packed.`] },
      { type: "paragraph", text: `Nothing is added at any stage, and there is no cream-separator shortcut in between. This takes considerably more time and labour per litre than machine separation, which is also part of why hand-churned bilona ghee typically costs more than mass-produced ghee - a matter of process and effort, not a lab claim.` },
      { type: "heading", text: `Bilona A2 Ghee vs Regular Commercial Ghee: A Side-by-Side Comparison` },
      { type: "paragraph", text: `Here is how the two generally compare, step by step. Individual brands and products can of course vary from this general picture.` },
      { type: "table", headers: [`What You're Comparing`, `Our Bilona A2 Ghee (Gir Cow / Desi Cow / Buffalo)`, `Typical Regular Commercial Ghee`], rows: [[`Milk source`, `Our own farm's Gir cow, desi cow or buffalo milk, selected per product`, `Often pooled milk from multiple, mixed or crossbred herds`], [`Butter extraction`, `Curd is hand-churned in a wooden bilona to separate makkhan (butter)`, `Cream is separated directly from milk by machine, skipping the curd-churning step`], [`Turning into ghee`, `Makkhan is slow-cooked gradually until it becomes clear, aromatic ghee`, `Cream or butter is usually heated in larger batches for faster throughput`], [`Batch size`, `Small batches, tied to what our own farm produces day to day`, `Usually large-volume batches made for wide retail distribution`], [`Traceability`, `Milk we source ourselves, on our own farm in Jaipur`, `Milk typically aggregated from many unnamed dairy sources before processing`], [`Price positioning`, `Reflects the labour-intensive hand process and smaller scale`, `Reflects lower per-unit cost from mechanised, large-scale processing`]], caption: `A general comparison of process and positioning - not a claim that one is medically superior to the other.` },
      { type: "callout", text: `Common Misconception: Is "A2 Ghee" Just a Marketing Label? It's a fair, skeptical question - and honestly, sometimes it is. The word "A2" has become popular enough that it gets printed on jars without much behind it. But the underlying science isn't invented: A2 beta-casein is a real, documented milk protein type, and indigenous cow breeds like Gir genuinely do produce milk that's predominantly A2. So the term itself isn't fiction - the real question is what's actually standing behind it on any given brand's shelf. For us, the claim we'd rather you weigh us on isn't just the word "A2" - it's that our milk comes from our own farm's Gir cows, desi cows and buffaloes in Jaipur, and that we hand-churn it into ghee using the bilona method rather than a machine cream separator. We don't publish lab certificates on our product pages, and we won't tell you a lab report exists unless it genuinely does for that specific batch - if you'd like to check, message us on WhatsApp and we'll share a matching report if one is available for that batch. We'd rather be upfront about what we do and don't have than let the word "A2" alone do the talking.` },
      { type: "heading", text: `Does A2 Ghee Have Extra Health Benefits Over Regular Ghee?` },
      { type: "paragraph", text: `We'd rather be direct here: we have no clinical studies or lab data to back specific health claims, and we won't make any. What we can honestly say is that in Ayurvedic tradition and everyday Indian households, ghee made from indigenous cow milk and slow bilona-churning has long been considered easier on digestion and gentler by many people, with desi cow milk in particular often spoken of this way in traditional practice. That is a matter of tradition and personal experience, not a medical guarantee, and it can vary from person to person. If you're choosing between A2 and regular ghee for a specific health reason, it's worth speaking with a doctor or nutritionist rather than relying on any brand's packaging claims - ours included.` },
      { type: "heading", text: `So, How Should You Decide Which Ghee to Buy?` },
      { type: "paragraph", text: `There's no single right answer here - it comes down to what matters most to you as a buyer.` },
      { type: "list", items: [`How the milk becomes ghee: choose hand-churned bilona ghee if you value the traditional slow process, or regular cream-separated ghee if speed and a lower price matter more.`, `Where the milk comes from: we can tell you ours is from our own farm's Gir cows, desi cows and buffaloes in Jaipur - it's worth asking any brand you're considering the same question.`, `Cow ghee vs buffalo ghee: our cow ghee (Gir or desi) tends to be lighter in colour with a more delicate aroma, while our buffalo ghee is richer and creamier - both are valid choices, and it comes down to taste.`, `Budget and quantity: hand-churned, small-batch ghee generally costs more per kilo than large-batch commercial ghee, reflecting the process and scale rather than any claim of one being medically better.`, `How much proof you personally need: if a published lab certificate matters to you, ask any brand directly what they can show you - including us; we're upfront that we don't publish these on our product pages.`] },
      { type: "heading", text: `Ordering and Delivery, If You Choose Ours` },
      { type: "paragraph", text: `If you'd like to try our bilona A2 ghee, you can order through the website cart or send a WhatsApp order using the pre-filled message on any product page, paying by Cash on Delivery or Razorpay online payment. If you're in Jaipur, our own team hand-delivers your order to your doorstep - it isn't handed off to a third-party courier - and this delivery is free. Elsewhere in Rajasthan, including Jodhpur, Udaipur and Kota, we ship by courier: weight-based charges of ₹59 to ₹199 apply on orders under ₹1,499, and delivery is free (up to 3kg) on orders of ₹1,499 or more. You can track any order on our Track Order page using your order number and phone number.` },
    ],
    faqs: [
      { question: `Is A2 ghee better than regular ghee for health?`, answer: `We can't say it's medically superior, and we won't claim that - there's no clinical data we can point to. A2 milk and bilona-made ghee have a long-standing place in Ayurvedic tradition, and many people believe it suits them better, but that's tradition and personal experience, not a proven health claim. It's worth choosing based on process, source and taste preference rather than an expected health outcome.` },
      { question: `Do you make cow ghee or buffalo ghee, and is your buffalo ghee also "A2"?`, answer: `We make ghee from Gir cow, desi cow and buffalo milk, all using the same bilona hand-churned process. The A1/A2 distinction is specific to cow milk protein, so we don't label our buffalo ghee as "A2" - buffalo milk has its own distinct protein profile. If you specifically want cow-milk A2 ghee, choose our Gir cow or desi cow ghee.` },
      { question: `Can I see a lab report or certification backing your A2 claim?`, answer: `We don't publish lab certificates or purity reports on our product pages. If you'd like to check for a specific batch, message us on WhatsApp and we'll share a matching report if one genuinely exists for that batch - we won't tell you one exists otherwise.` },
      { question: `Why does bilona A2 ghee cost more than regular ghee in stores?`, answer: `Hand-churning butter from curd in a wooden bilona, then slow-cooking it into ghee, takes far more time and labour per batch than the machine cream-separation used for most regular commercial ghee. The price difference reflects that process and our smaller, farm-based batch sizes - it isn't a claim that one ghee is medically better than the other.` },
      { question: `How do I order your A2 ghee, and what are the delivery options?`, answer: `You can order through our website cart or via WhatsApp using the pre-filled message on any product page, and pay by Cash on Delivery or Razorpay. Within Jaipur, our own team hand-delivers for free. Elsewhere in Rajasthan, including Jodhpur, Udaipur and Kota, delivery is by courier - ₹59 to ₹199 on orders under ₹1,499, and free (up to 3kg) on orders of ₹1,499 or more. You can track any order using your order number and phone number on the Track Order page.` },
    ],
  },
  {
    slug: `bilona-ghee-process-explained`,
    title: `Bilona Ghee Process Explained: How Our Farm Ghee Is Made Step by Step`,
    metaDescription: `Learn the real Bilona ghee process step by step: milk selection, curd culturing, hand-churning with a wooden bilona, and slow-cooking into ghee.`,
    targetKeyword: `Bilona ghee process explained`,
    eyebrow: `From Curd to Ghee, By Hand`,
    intro: `The Bilona ghee process turns milk into ghee through four traditional stages: selecting Gir cow, Desi cow or buffalo milk, culturing it into curd overnight, hand-churning that curd with a wooden bilona to separate butter, and slow-cooking the butter into clear, golden ghee. Unlike a machine cream-separator method, which pulls cream directly from milk, every stage here is done manually and takes real time — no shortcuts, nothing added.`,
    heroImage: `/images/founder/founder-bilona-churning.png`,
    heroAlt: `Hand-churning curd with a traditional wooden bilona at Organic Jaipur Store`,
    category: `GHEE` as CategoryValue,
    publishDate: `September 15, 2026`,
    sections: [
      { type: "heading", text: `What Is the Bilona Method, Exactly?` },
      { type: "paragraph", text: `Bilona simply refers to the traditional wooden churner used to separate butter from curd by hand. The "Bilona method" of making ghee is named after this tool, and it describes a specific sequence: milk is first turned into curd, the curd is churned to get butter, and that butter is then cooked down into ghee. This is different from starting with cream that has been mechanically separated from milk. It's a slower, more hands-on way of making ghee that has traditionally been followed in Indian homes for generations, and it's the process we follow on our own farm in Jaipur.` },
      { type: "heading", text: `How Is Bilona Ghee Made? The Complete 4-Step Process` },
      { type: "paragraph", text: `Here is exactly how we make our Bilona ghee, from milk to jar, in the order it actually happens.` },
      { type: "list", items: [`Step 1 — Milk Selection: We start by choosing the milk itself. Depending on the product, we use milk from Gir cows, Desi cows, or buffaloes raised on our own farm in Jaipur. The type of milk is decided upfront, because it shapes everything that follows — the curd, the butter, and finally the ghee.`, `Step 2 — Curd Culturing: The selected milk is left to culture and rest naturally overnight, turning into curd (dahi). This isn't rushed or force-set — the milk needs undisturbed time to develop into proper curd, which is the actual starting point for Bilona ghee, unlike methods that go straight from milk to cream.`, `Step 3 — Hand-Churning With a Wooden Bilona: The curd is churned by hand using a traditional wooden bilona (churner), worked slowly and steadily until butter (makkhan) separates from the buttermilk. This manual churning step is what gives the method its name, and it is fundamentally different from using a machine cream separator, which extracts cream directly from raw milk without ever making curd.`, `Step 4 — Slow-Cooking Into Ghee: The fresh butter (makkhan) collected from churning is heated gradually on a slow flame. As it cooks, moisture evaporates and the butter transforms into clear, aromatic, golden ghee. Once it reaches the right stage, it is filtered and packed — with nothing added at any point in the process.`] },
      { type: "heading", text: `Why Does Each Traditional Step Matter?` },
      { type: "paragraph", text: `Every stage in the Bilona process takes time, and that's by design, not an inefficiency. Culturing milk into curd overnight lets natural fermentation happen at its own pace — there is no way to skip straight from milk to butter without first passing through curd. Hand-churning that curd with a wooden bilona instead of a machine is slower and physically demanding, often taking hours of manual effort per batch, but it's how butter has traditionally been separated from curd in Indian kitchens for generations.` },
      { type: "paragraph", text: `The final slow-cooking step matters just as much. Heating the butter gradually, instead of rushing it over high heat, gives moisture the time it needs to fully leave and lets the milk solids brown gently — this is what produces clear, deep-golden ghee with its characteristic aroma. A cream-separator machine method works differently from the very first step: it separates cream directly from milk using a mechanical separator, without any curd-culturing or hand-churning stage at all. That route is quicker and easier to scale, which is exactly why it's common among larger commercial ghee makers — but it is a genuinely different process, not simply a faster version of the same one.` },
      { type: "heading", text: `Bilona Hand-Churned vs Cream-Separator Machine Ghee: Side by Side` },
      { type: "paragraph", text: `Because the two methods start from different points and involve different amounts of manual work, they're worth comparing directly.` },
      { type: "table", headers: [`Aspect`, `Bilona Hand-Churned Method (our process)`, `Cream-Separator Machine Method`], rows: [[`Starting point`, `Milk is first cultured into curd overnight`, `Cream is separated directly from raw milk`], [`How butter is separated`, `Curd is churned slowly by hand with a wooden bilona`, `A mechanical separator extracts cream, which is then processed by machine`], [`Time taken per batch`, `Roughly a full day or more — overnight culturing, plus hours of hand-churning and slow-cooking`, `A matter of minutes to separate cream, with faster mechanical processing after`], [`Effort involved`, `Manual, hands-on labour at the churning stage`, `Largely automated`], [`Typical texture/aroma outcome*`, `Often described as having a more granular texture and a pronounced, roasted aroma`, `Often smoother in texture and milder in aroma`]], caption: `Bilona hand-churned ghee vs cream-separator machine ghee` },
      { type: "paragraph", text: `*These are general traits people commonly describe when comparing the two methods, not a claim about nutritional quality or health benefit — both are, at the end of the day, ghee made from milk fat.` },
      { type: "heading", text: `Is "Homemade-Style" Ghee Just a Marketing Label? Common Misconceptions` },
      { type: "paragraph", text: `It's a fair question. Words like "hand-churned" and "bilona" have become common on ghee packaging, so it's reasonable to wonder whether they describe anything real or are simply added for effect. The honest answer is that it depends entirely on whether the process behind the label actually happened.` },
      { type: "callout", text: `Myth: "Homemade-style" or "Bilona" ghee is just a marketing term, and all ghee is essentially made the same way. Fact: There is a real, checkable procedural difference. Bilona ghee starts with milk cultured into curd overnight, which is then hand-churned with a wooden churner to get butter — an extra stage that a cream-separator machine method skips entirely by pulling cream straight from milk. If a product hasn't gone through curd-culturing and hand-churning, it isn't Bilona ghee, regardless of what the label says.` },
      { type: "paragraph", text: `For our own ghee, that means milk from our farm's Gir cows, Desi cows or buffaloes is rested into curd first, churned by hand with a wooden bilona, and only then slow-cooked into ghee — with no cream-separator shortcut and nothing added along the way. We should also be upfront that we don't currently publish lab certificates or third-party purity test reports on our product pages. If a batch-specific report happens to exist, we're happy to share it on request over WhatsApp, but we won't claim a certification or test result we don't actually have. What we can stand behind, and what you can genuinely verify by asking us, is the process itself — the real, procedural difference between Bilona ghee and ghee made by cream separation.` },
      { type: "heading", text: `What Does "A2 Ghee" Mean for Our Gir Cow and Desi Cow Milk?` },
      { type: "paragraph", text: `You may see ghee made from indigenous cow breeds like Gir and Desi cow marketed as "A2 ghee." The term refers to the type of milk these breeds are commonly associated with, as distinct from milk from certain other cattle breeds. On our farm, milk from Gir cows and Desi cows is used to make this style of ghee, while our buffalo milk ghee is offered separately as its own product. We're describing this as a matter of breed and milk source, not as a health or medical claim, and we'd encourage you to look into the underlying topic independently, and to treat any specific health-benefit claim you come across elsewhere with a healthy dose of scepticism unless it comes from a source you trust.` },
      { type: "heading", text: `How to Get Bilona Ghee From Our Farm to Your Door` },
      { type: "paragraph", text: `Once a batch is ready, ordering is straightforward. You can add it to your cart on our website and check out directly, or place an order over WhatsApp using the pre-filled message available on each product page — whichever works better for you. Payment can be made via Cash on Delivery or online through Razorpay. Within Jaipur city, our own team hand-delivers orders to your doorstep at no charge, rather than handing them off to a third-party courier. For addresses elsewhere in Rajasthan, including Jodhpur, Udaipur and Kota, we ship by courier, with weight-based charges between ₹59 and ₹199 on orders under ₹1,499, and free shipping (up to 3 kg) on orders of ₹1,499 and above. Once your order is placed, you can track it any time using your order number and phone number on our Track Order page.` },
    ],
    faqs: [
      { question: `How long does it take to make Bilona ghee?`, answer: `A single batch typically takes roughly a day or more from start to finish — the milk first needs to culture into curd overnight, then it's hand-churned for hours with a wooden bilona, and finally slow-cooked into ghee. This is considerably longer than a cream-separator machine method, where cream can be separated from milk in a matter of minutes.` },
      { question: `What milk is used for Bilona ghee?`, answer: `We use milk from Gir cows, Desi cows or buffaloes raised on our own farm in Jaipur, with the type selected per product.` },
      { question: `Is Bilona ghee the same as regular ghee?`, answer: `Both are ghee made from milk fat, but the process differs. Bilona ghee is made by first culturing milk into curd, then hand-churning that curd into butter with a wooden churner before slow-cooking it into ghee. Many commercial ghee makers instead use a cream separator to pull cream directly from milk, skipping the curd-culturing and hand-churning stages.` },
      { question: `Does this ghee come with a lab certificate or purity test report?`, answer: `We don't publish lab certificates or purity test reports on our product pages. If a batch-specific report happens to exist, we can share it on request over WhatsApp, though we can't guarantee one exists for every batch.` },
      { question: `Can I track my ghee order after I place it?`, answer: `Yes. Once your order is placed, you can track it on our Track Order page using your order number and the phone number you ordered with.` },
    ],
  },
  {
    slug: `kachi-ghani-vs-refined-mustard-oil`,
    title: `Kachi Ghani vs Refined Mustard Oil: What's the Difference?`,
    metaDescription: `Kachi ghani vs refined mustard oil: see how wood-press extraction differs from industrial refining, how to store it, and how to pick black or yellow oil.`,
    targetKeyword: `kachi ghani vs refined mustard oil`,
    eyebrow: `Kachi Ghani Mustard Oil, Explained`,
    intro: `Kachi ghani mustard oil is crushed from mustard seed on a traditional wooden ghani (cold press) at low speed, with no added heat or chemical solvents, while refined mustard oil is extracted using industrial heat and solvent-based processing and then further refined. That's why kachi ghani oil keeps a sharper, stronger natural pungency that refined oil largely loses along the way.`,
    heroImage: `/images/founder/founder-mustard-ghani-press.png`,
    heroAlt: `Traditional wooden ghani pressing mustard oil in Rajasthan`,
    category: `MUSTARD_OIL` as CategoryValue,
    publishDate: `September 12, 2026`,
    sections: [
      { type: "heading", text: `What Exactly Is Kachi Ghani Mustard Oil?` },
      { type: "paragraph", text: `"Kachi ghani" refers to the traditional wooden press (ghani) that crushes mustard seed slowly, at low speed, without adding external heat or chemical solvents. The seed is pressed mechanically, and the oil that separates out is simply filtered and bottled, with nothing added. At Organic Jaipur Store, the mustard we press is grown on our own farm in Jaipur, and we make both a black mustard oil, which is stronger and sharper, and a milder yellow mustard oil, using this same wooden cold-press method. Because there's no chemical extraction step involved, kachi ghani oil holds on to much of the seed's natural pungency, colour and aroma — the sharp, nose-tingling smell many Rajasthani households associate with real sarson ka tel.` },
      { type: "heading", text: `How Is Refined Mustard Oil Made, and Why Does It Smell So Different?` },
      { type: "paragraph", text: `Industrially refined mustard oil is generally produced at a much larger scale. After the seed is crushed, the remaining oil is typically pulled out using heat and chemical solvents to extract as much oil as possible from the residue, and the resulting crude oil then goes through further refining steps — such as neutralising, bleaching and deodorising — before it's bottled. This process is built to produce a lighter-coloured, more neutral-smelling oil at a lower cost per litre and larger scale. The trade-off is that a good deal of the seed's original pungency and characteristic mustard aroma gets stripped out along the way, which is why refined mustard oil generally smells and tastes noticeably milder than kachi ghani oil.` },
      { type: "heading", text: `Kachi Ghani vs Refined Mustard Oil: Side-by-Side Comparison` },
      { type: "paragraph", text: `Here's how the two compare on the points that matter most when you're cooking at home:` },
      { type: "table", headers: [`Aspect`, `Kachi Ghani Mustard Oil`, `Refined Mustard Oil`], rows: [[`Extraction method`, `Crushed slowly on a traditional wooden ghani (cold press)`, `Crushed, then typically extracted further using heat and chemical solvents`], [`Heat involved`, `No external heat added during pressing`, `Heat is used during extraction and refining`], [`Aroma & pungency`, `Strong, sharp, distinctly mustard-forward`, `Much milder; a lot of the natural pungency is refined out`], [`Colour & clarity`, `Deeper amber/reddish tone; may look less uniformly clear`, `Lighter, more uniform colour`], [`Common use in Rajasthani cooking`, `Tempering (tadka), pickles, achari dishes — where a sharp mustard note is wanted`, `Everyday light cooking where a milder, more neutral taste is preferred`]], caption: `A general comparison based on how each oil is typically processed.` },
      { type: "heading", text: `Does Kachi Ghani Mustard Oil Expire Faster? How Should You Store It?` },
      { type: "paragraph", text: `This is one of the questions we hear most often, and the honest answer is that there's no dramatic, verified difference in how quickly a well-stored bottle of kachi ghani oil goes off compared to refined oil — what matters far more is how it's stored. Because kachi ghani oil isn't chemically refined, some people assume it must spoil sooner, but we don't have any tested figures that put a specific number on this, so we won't invent a shelf-life claim. What we can say generally is that any cooking oil, kachi ghani or refined, holds up best when it's kept away from heat, light and moisture.` },
      { type: "list", items: [`Store the bottle in a cool, dry place, away from direct sunlight`, `Keep the cap tightly closed after each use to limit air exposure`, `Avoid keeping the bottle right next to your stove or another heat source`, `Pour directly or use a clean, dry spoon — avoid letting water or food particles get into the bottle`, `Once opened, try to use the oil within a reasonable time rather than letting it sit for months`] },
      { type: "heading", text: `Black or Yellow Kachi Ghani Mustard Oil: Which One Should You Pick?` },
      { type: "paragraph", text: `Both our black and yellow mustard oils are made the same way — cold-pressed on a wooden ghani from mustard seed grown on our own farm — so the choice really comes down to how strong a flavour you want. Our black mustard oil is the sharper, stronger option, closer to what many traditional Rajasthani kitchens have used for generations in tempering, pickles and achari-style cooking, where a bold mustard bite is part of the dish. Our yellow mustard oil is milder, so it suits everyday cooking or households that want the character of kachi ghani oil without as much pungency. If you already cook with sarson ka tel regularly and enjoy its natural sharpness, the black oil is usually the closer match; if you're newer to kachi ghani oil or prefer a gentler taste, the yellow one is a good place to start.` },
      { type: "heading", text: `Common Misconceptions About Kachi Ghani Mustard Oil` },
      { type: "list", items: [`Myth: "Kachi ghani" just means any mustard oil sold loose or unbranded. Fact: it specifically refers to the wooden cold-press extraction method — no added heat, no chemical solvents — regardless of how it's packaged.`, `Myth: A cloudy or slightly sediment-heavy oil is spoiled. Fact: minimally processed oils can look less "polished" than refined oil simply because they haven't been through the bleaching and clarifying steps refined oil goes through.`, `Myth: Refined oil is automatically "purer" because it looks cleaner and smells milder. Fact: refined oil goes through additional heat and solvent-based processing steps — a neutral smell reflects processing, not purity.`, `Myth: A strong smell means the oil has been adulterated. Fact: the sharp, pungent aroma of kachi ghani oil is a natural characteristic of cold-pressed mustard oil, not a sign of impurity.`] },
      { type: "callout", text: `A simple way to think about it: refined oil is designed to be neutral and consistent at scale, while kachi ghani oil is pressed to keep as much of the seed's natural character — flavour, aroma and colour — intact. Neither is "fake" or "impure" by default; they're just made differently.` },
      { type: "heading", text: `Where to Buy Genuine Kachi Ghani Mustard Oil from Jaipur` },
      { type: "paragraph", text: `The mustard we press for both our black and yellow oils is grown on our own farm in Jaipur, so the seed-to-bottle journey stays within a process we manage directly. You can order through our website's cart and checkout, or send a WhatsApp order using the pre-filled message available on the product page — whichever is easier for you. Payment can be made via Cash on Delivery or Razorpay online payment. If you're in Jaipur, our own team hand-delivers your order straight to your doorstep at no extra cost, rather than handing it off to a third-party courier. For addresses elsewhere in Rajasthan, including Jodhpur, Udaipur and Kota, we ship by courier — weight-based charges from ₹59 to ₹199 apply on orders under ₹1,499, and shipping is free (up to 3kg) on orders of ₹1,499 or more. Once your order is placed, you can track it any time from the Track Order page using your order number and phone number. If you'd like to see a lab report for a specific batch, you're welcome to ask us on WhatsApp — we'll share one if a matching report exists for that batch.` },
    ],
    faqs: [
      { question: `Is kachi ghani mustard oil the same as cold-pressed mustard oil?`, answer: `Yes. "Kachi ghani" describes the traditional wooden press method used to extract the oil at low speed without added heat, which is generally what people mean when they say "cold-pressed" mustard oil.` },
      { question: `Why is refined mustard oil usually cheaper than kachi ghani oil?`, answer: `Refined mustard oil is typically produced at a larger industrial scale using heat and solvent-based extraction to pull more oil from the seed, along with further refining steps. That scale and process generally bring the cost per litre down compared to the slower, lower-yield wooden cold-press method.` },
      { question: `Does kachi ghani mustard oil need to be refrigerated?`, answer: `No, refrigeration isn't necessary. Like most cooking oils, it keeps best in a cool, dry place away from direct sunlight, with the cap kept tightly closed between uses.` },
      { question: `Which is better for cooking, black or yellow kachi ghani mustard oil?`, answer: `It comes down to taste. Black mustard oil is stronger and sharper and suits traditional Rajasthani dishes like tempering and pickles, while yellow mustard oil is milder and works well for everyday cooking.` },
      { question: `Can I see a lab or purity report for your mustard oil?`, answer: `We don't publish lab reports on our product pages, but you're welcome to ask us on WhatsApp — if a matching report exists for the batch you've received, we'll share it with you.` },
    ],
  },
  {
    slug: `how-to-test-honey-purity-at-home`,
    title: `How to Test Honey Purity at Home (And Why It's Not Reliable)`,
    metaDescription: `Learn 3 common home tests for honey purity (water, flame, crystallisation) and why experts say they can't reliably catch modern syrup adulteration.`,
    targetKeyword: `how to test honey purity at home`,
    eyebrow: `Honey Purity Tests, Explained`,
    intro: `Home tests like the water test and flame test can give you a rough, informal read on a jar of honey, but they were never designed to catch the sugar-syrup adulteration that worries most buyers today. Signs like crystallisation tell you about how the honey was processed, not whether it's pure — a real purity verdict ultimately needs laboratory testing, not a glass of water.`,
    heroImage: `/images/founder/founder-apiary-honeycomb.png`,
    heroAlt: `Raw honeycomb from managed beehives at Organic Jaipur Store farm`,
    category: `HONEY` as CategoryValue,
    publishDate: `September 10, 2026`,
    sections: [
      { type: "heading", text: `What Do People Actually Mean by 'Testing Honey Purity at Home'?` },
      { type: "paragraph", text: `Concerns about honey adulterated with cheap sugar syrups have made a lot of buyers cautious, and a few DIY checks — the water test, the flame test, and watching how honey behaves in the jar over time — get shared often as ways to 'know' if a jar is genuine. They're worth understanding, because they're not completely meaningless, but they're also not the final word. Below, we walk through what each test actually claims to detect and why food-quality reviewers generally consider them insufficient on their own, before explaining what our own raw honey is, and isn't.` },
      { type: "heading", text: `The Water Test: How It's Done and What It Can (and Can't) Show` },
      { type: "paragraph", text: `The idea behind the water test is simple: drop a spoonful of honey into a glass of room-temperature water. The claim is that genuine honey, being dense, sinks to the bottom as a distinct blob rather than dissolving quickly, while honey diluted with plain water or cheap syrup disperses and clouds the water faster. In practice, this test can sometimes flag very crude dilution with plain water. It was never built to catch the kind of adulteration most buyers actually worry about today — refined sugar syrups (such as rice or invert syrups) manufactured specifically to match honey's density and behaviour. Against those, the water test typically can't tell the difference.` },
      { type: "list", items: [`Fill a clear glass with room-temperature water.`, `Drop in a spoonful of honey without stirring.`, `Watch for one to two minutes.`, `Note whether it holds together at the bottom or disperses into the water — then remember this alone doesn't confirm purity.`] },
      { type: "heading", text: `The Flame Test: Is It Safe or Accurate?` },
      { type: "paragraph", text: `The flame test involves dipping a matchstick or a piece of cotton wick in honey and trying to light it. The idea is that honey with very little moisture catches fire and burns steadily, while honey diluted with water or syrup sputters, smokes, or won't light because of the extra moisture. The problem is that natural moisture content in honey varies depending on the flower source, the season and how it's been stored, so a completely genuine jar can still fail this test simply for being a touch more humid than another batch. It also involves an open flame near a sticky, flammable substance, which is a reason to be careful even when trying it out of curiosity. Like the water test, it isn't considered a dependable stand-in for real testing.` },
      { type: "heading", text: `Does Honey Crystallising or Turning Cloudy Mean It's Fake?` },
      { type: "paragraph", text: `A jar of honey that goes from clear and runny to pale, grainy or fully solid over a few weeks or months often makes people suspicious that something's wrong. For raw, lightly filtered honey, this is actually expected: because it hasn't been heavily heat-treated or ultra-filtered to strip out natural glucose crystals, it can crystallise or turn cloudy over time, especially in cooler weather. On its own, crystallisation doesn't prove a honey is pure, and its absence doesn't prove it's fake either — it mainly tells you something about how the honey was processed and stored, not what it's actually made of. Some heavily processed, blended honeys are specifically treated to resist crystallising and stay liquid on the shelf indefinitely; that's a processing choice, not evidence of authenticity by itself.` },
      { type: "callout", text: `Myth: 'If a honey passes the water test, the flame test, and never crystallises, it must be 100% pure.' Fact: none of these home checks are validated against the sugar-syrup adulteration methods that concern most buyers today — the syrups used are often engineered to mimic honey's density, colour and even burn behaviour. A jar can sail through every kitchen test and still not be pure, while a completely natural raw honey can 'fail' a folk test (for instance, by crystallising, or by having a slightly different consistency from the last jar) simply because natural honey varies batch to batch. We treat these tests as interesting kitchen experiments, not as a purity verdict — on any brand's honey, including our own.` },
      { type: "heading", text: `Why Are Home Tests Considered Unreliable Against Modern Adulteration?` },
      { type: "paragraph", text: `The honey adulteration that food-safety researchers are actually concerned about today isn't a jar with a splash of tap water added — it's honey blended with manufactured sugar syrups engineered to closely match honey's density, sugar ratio and even some basic physical behaviours. Reliably telling these apart from real honey generally needs laboratory methods that examine the honey's chemical make-up, not just how it looks in a glass of water or how it burns on a wick. That's a meaningful gap: a test you can do in your kitchen in five minutes and a test that needs laboratory equipment are simply not solving the same problem, which is why we're upfront that home tests have real limits.` },
      { type: "heading", text: `Raw Honey vs Heavily Processed Honey: A Side-by-Side Comparison` },
      { type: "table", headers: [`Aspect`, `Raw, Lightly Filtered Honey`, `Heavily Processed / Blended Commercial Honey`], rows: [[`Typical processing`, `Lightly filtered only, to remove wax and physical debris; no added sugar or syrup`, `Often heat-treated and heavily micro-filtered, and in some cases blended with sugar syrups`], [`Crystallisation behaviour`, `Can naturally crystallise or turn cloudy over time, especially in cooler storage — a normal characteristic, not a defect`, `Often engineered or treated to stay liquid and clear indefinitely on the shelf`], [`What that behaviour tells you`, `Reflects minimal processing, not a purity guarantee by itself`, `Reflects processing choices, not proof of authenticity either way`], [`How to actually confirm purity`, `Not determined by kitchen tests — requires lab testing`, `Not determined by kitchen tests — requires lab testing`]], caption: `Raw, lightly filtered honey vs heavily processed/blended commercial honey (general comparison)` },
      { type: "heading", text: `What Our Raw Honey From Organic Jaipur Store Actually Is` },
      { type: "paragraph", text: `Our honey comes from our own managed beehives on our farm in Jaipur. Once harvested, it's only lightly filtered — enough to strain out physical bits like wax fragments — with nothing added at any stage: no sugar, no syrup. Because it isn't heavily processed, don't be surprised if it turns cloudy or partly crystallises in the jar after some time in storage, particularly in cooler months; that's a normal characteristic of raw honey, not a defect, and gently warming the jar (for instance, standing it in warm water) usually brings it back to a smoother, pourable texture. We don't publish lab certificates on our product pages today. If a matching batch or lab report exists for the specific jar you've ordered, we're happy to share it on request over WhatsApp — though we can't promise a report exists for every batch, and we won't claim one does when it doesn't.` },
      { type: "heading", text: `So What Should You Actually Do If You Want Certainty?` },
      { type: "paragraph", text: `If what you need is a definitive, lab-grade purity verdict, no home test — ours or anyone else's — is going to get you there; that's a job for an accredited food-testing laboratory, not a kitchen glass of water. What a home test can reasonably do is satisfy some curiosity, as a rough, informal check. Beyond that, it helps to judge a jar of honey by what you can actually verify about it: where it comes from, how (and how little) it's processed, and whether the seller is straightforward about both. That's the basis we'd rather be judged on — our own beehives, light filtering only, nothing added — instead of a purity claim we can't back up with a report we don't have.` },
      { type: "list", items: [`Where are the beehives, and are they managed by the seller directly or bought in from elsewhere?`, `Is anything added during processing — sugar, syrup, extra heat treatment?`, `Will the seller share a batch-specific lab report on request, if one exists?`, `Does the seller explain honey crystallising as a normal, expected change — or treat it as something to hide?`] },
    ],
    faqs: [
      { question: `Can the water test alone confirm my honey is pure?`, answer: `No. It can flag honey that's been diluted with a lot of plain water, but it isn't built to detect the sugar-syrup adulterants used in modern blending, so a jar can pass the water test and still not be pure honey.` },
      { question: `Why did my raw honey turn cloudy or solid in the jar?`, answer: `That's natural crystallisation, common in raw, lightly filtered honey, especially in cooler weather. It's generally a sign of minimal processing, not spoilage or contamination — though on its own it doesn't prove purity either.` },
      { question: `Does Organic Jaipur Store's honey come with a lab-certified purity report?`, answer: `We don't publish lab certificates on our product pages. If a matching batch report exists for the honey you've ordered, we can share it on request over WhatsApp, but we can't guarantee a report exists for every batch.` },
      { question: `Is the flame test a reliable way to check honey at home?`, answer: `It's a widely shared home test, but its result depends heavily on the honey's natural moisture content, which varies by floral source and storage — so it isn't considered a dependable purity indicator by itself, and it also carries an obvious fire-safety caution.` },
      { question: `What actually makes Organic Jaipur Store's honey 'raw'?`, answer: `It's harvested from our own managed beehives on our farm in Jaipur and only lightly filtered to remove physical impurities like wax — with no added sugar or syrup at any stage.` },
    ],
  },
];
