export const MAKING_PROCESSES = [
  {
    slug: "bilona-ghee",
    label: "Bilona Ghee",
    category: "GHEE",
    eyebrow: "Traditional Bilona Method",
    title: "From Fresh Milk to Golden Ghee",
    intro: "Four stages: cultured curd, patient hand-churning and slow cooking, with no cream-separator shortcuts.",
    banner: "/images/founder/founder-bilona-churning.png",
    strip: "/images/process/ghee-traditional-strip-v2.jpg",
    stepImages: [
      "/images/generated/journey-own-farm-v2.png",
      "/images/generated/journey-curd-v2.png",
      "/images/generated/journey-bilona-v2.png",
      "/images/generated/journey-slow-ghee-v2.png",
    ],
    accent: "Milk · Curd · Bilona · Ghee",
    steps: [
      { title: "Milk Selected for Each Variety", detail: "Gir cow, Desi cow or buffalo milk is selected according to the ghee being made and checked before processing.", note: "Check the individual product for its milk source and ask about the available batch." },
      { title: "Curd Is Set Naturally", detail: "The milk is cultured and rested in suitable conditions until it becomes curd with the right body and aroma.", note: "This cultured-curd stage gives bilona ghee its traditional character." },
      { title: "Hand-Churned With Bilona", detail: "The curd is churned slowly to separate makkhan. This is fundamentally different from making ghee directly from separated cream.", note: "Slow churning separates the butter without rushing the process." },
      { title: "Slow-Cooked and Filtered", detail: "Makkhan is heated gradually until moisture leaves and clear aromatic ghee forms, then it is filtered and packed.", note: "Colour, aroma and clarity are reviewed before packing." },
    ],
  },
  {
    slug: "cold-pressed-oil",
    label: "Cold-Pressed Oil",
    category: "MUSTARD_OIL",
    eyebrow: "Traditional Oil Extraction",
    title: "Seed to Bottle, No Refining Shortcuts",
    intro: "Ingredient preparation, gradual pressing, natural settling and filtration. The selected product specifies its ingredient and wood-pressed, stone-pressed or cold-pressed method.",
    banner: "/images/founder/founder-mustard-ghani-press.png",
    strip: "/images/process/oil-traditional-strip-v2.jpg",
    stepImages: [
      "/images/process/oil-sort-v3.png",
      "/images/process/oil-press-v3.png",
      "/images/process/oil-settle-v3.png",
      "/images/process/oil-pack-v3.png",
    ],
    accent: "Seed · Ghani · Settle · Bottle",
    steps: [
      { title: "Ingredients Are Prepared", detail: "The ingredient for the selected oil is cleaned and sorted before pressing. Our range includes mustard, groundnut, sunflower and coconut oils.", note: "Read the product name and ingredient list to choose the oil you need." },
      { title: "Gradual Pressing", detail: "The selected oil uses its stated wood-pressed, stone-pressed or cold-pressed method without chemical solvents.", note: "Controlled extraction helps retain the seed's distinctive aroma." },
      { title: "Oil Rests Naturally", detail: "Freshly pressed oil is allowed to settle so heavier natural particles can separate without aggressive processing.", note: "Settling reduces the need for harsh clarification." },
      { title: "Filtered and Hygienically Packed", detail: "The settled oil is filtered, checked for expected colour and aroma, then filled into clean food-safe bottles.", note: "Each packed batch remains linked to its production details." },
    ],
  },
  {
    slug: "raw-honey",
    label: "Raw Honey",
    category: "HONEY",
    eyebrow: "Minimal Handling",
    title: "From the Hive, Handled With Restraint",
    intro: "Our own managed beehives and gentle filtration: no heating, no processing beyond what's needed for cleanliness.",
    banner: "/images/founder/founder-apiary-honeycomb.png",
    strip: "/images/process/honey-traditional-strip-v2.jpg",
    stepImages: [
      "/images/process/honey-hive-v3.png",
      "/images/process/honey-inspect-v3.png",
      "/images/process/honey-filter-v3.png",
      "/images/process/honey-fill-v3.png",
    ],
    accent: "Hive · Inspect · Filter · Fill",
    steps: [
      { title: "Honey From Our Managed Beehives", detail: "The beehives are installed and managed on our own farm, giving us direct visibility into hive care and each collected batch.", note: "There is no anonymous honey supply chain between the hive and us." },
      { title: "Incoming Batch Inspection", detail: "Each lot is reviewed for expected appearance, aroma, consistency and visible cleanliness before further handling.", note: "Unusual batches are held back for review." },
      { title: "Gentle Physical Filtration", detail: "Honey passes through a fine filter to remove wax and physical impurities without unnecessary refining steps.", note: "The purpose is cleanliness, not stripping character." },
      { title: "Clean Filling and Sealing", detail: "Approved honey is filled into sanitised jars, sealed and labelled so the packed product can be traced to its batch.", note: "Pack integrity is checked before dispatch." },
    ],
  },
  {
    slug: "traditional-pickles",
    label: "Pickles & Chutney",
    category: "PICKLES",
    eyebrow: "Traditional Pickles & Chutney",
    title: "Ingredients, Spice and Time in Balance",
    intro: "Farm-grown produce, measured spice and natural maturation, not instant flavouring.",
    banner: "/images/generated/process-pickle-hero-v2.png",
    strip: "/images/process/pickle-traditional-strip-v2.jpg",
    stepImages: [
      "/images/process/pickle-select-v3.png",
      "/images/process/pickle-measure-v3.png",
      "/images/process/pickle-mature-v3.png",
      "/images/process/pickle-seal-v3.png",
    ],
    accent: "Select · Mix · Mature · Seal",
    steps: [
      { title: "Ingredients From Our Own Farm", detail: "Mango, lemon, chilli and other seasonal pickle ingredients grown on our farm are cleaned, sorted and prepared for each small batch.", note: "We grow the main produce ourselves and select it at the right stage for pickling." },
      { title: "Spices and Oil Are Measured", detail: "Prepared ingredients are mixed with the recipe's spices, salt and oil in controlled proportions.", note: "Measured recipes keep flavour and preservation consistent." },
      { title: "The Batch Matures Naturally", detail: "The mixed pickle is rested so salt, spice and oil can penetrate while its full flavour develops over time.", note: "Maturation is observed rather than hurried." },
      { title: "Final Review and Sealing", detail: "Taste, aroma, texture and jar hygiene are checked before the matured pickle is filled and securely sealed.", note: "Only approved jars move to customer orders." },
    ],
  },
] as const;

export type MakingProcess = (typeof MAKING_PROCESSES)[number];
