import Image from "next/image";
import Link from "next/link";
import AnimatedSection from "@/components/AnimatedSection";

export const metadata = { title: "Our Quality Promise: What Gets Checked, and When", description: "The ingredient check, process check, finished-batch check and traceability record every Organic Jaipur product goes through before it ships." };

const PROMISES = [
  ["Ingredient Check", "Milk, seed and honey are inspected for freshness the moment they enter a batch, not after."],
  ["Process Check", "Bilona churning, wooden-ghani pressing and honey filtration are watched step by step, not left to guesswork."],
  ["Finished-Batch Check", "Taste, aroma, colour and packaging are reviewed before a batch is approved for sale."],
  ["Batch Traceability", "Every jar can be traced back to the batch it came from, so any question has a real answer."],
] as const;

export default function QualityPromisePage() {
  return <main className="bg-[#fffdf8]"><section className="relative min-h-[500px] overflow-hidden bg-forest-900 text-white"><Image src="/images/generated/banner-shop-farm-v3.jpg" alt="Organic Jaipur products at a Rajasthan farm" fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,29,20,.9)_0%,rgba(8,29,20,.56)_48%,rgba(8,29,20,.05)_82%)]"/><div className="relative mx-auto flex min-h-[500px] max-w-7xl items-center px-5 py-20 sm:px-8"><AnimatedSection className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-honey-400">Quality, Without the Noise</p><h1 className="mt-5 font-display text-5xl leading-none sm:text-7xl">Our Quality Promise</h1><p className="mt-3 font-display text-lg italic text-honey-400/80">Bharose Ki Buniyad</p><p className="mt-6 max-w-xl text-base leading-7 text-white/68">See what we check before a product is packed. Ask for the latest available batch information before you order.</p></AnimatedSection></div></section><section className="mx-auto max-w-6xl px-4 py-20 sm:px-6"><div className="grid gap-5 md:grid-cols-2">{PROMISES.map(([title, copy], index) => <AnimatedSection key={title} delay={index * .08}><article className="h-full rounded-[1.6rem] border border-forest-900/10 bg-white p-8"><span className="text-2xl text-honey-500">✦</span><h2 className="mt-8 font-display text-2xl text-forest-900">{title}</h2><p className="mt-3 leading-7 text-foreground/65">{copy}</p></article></AnimatedSection>)}</div><AnimatedSection delay={.2}><div className="mt-10 rounded-[2rem] bg-[#e8f0de] p-8 text-center sm:p-12"><h2 className="font-display text-3xl text-forest-900">Check the Details Before You Buy</h2><p className="mx-auto mt-3 max-w-xl text-foreground/65">Ask our Jaipur team for the latest available batch information, ingredients or delivery time on WhatsApp.</p><div className="mt-6 flex flex-wrap items-center justify-center gap-3"><Link href="/contact" className="inline-flex rounded-full bg-forest-900 px-6 py-3 text-sm font-semibold text-cream hover:bg-forest-800">Ask on WhatsApp →</Link><Link href="/products" className="inline-flex rounded-full border border-forest-900/15 px-6 py-3 text-sm font-semibold text-forest-900 hover:bg-forest-900/5">Shop Now →</Link></div></div></AnimatedSection></section></main>;
}
